### ISSUE TITLE
Move parser to a separate repo

### ISSUE THREAD

**Issue by ChALkeR** [qmlweb/qmlweb#173]
This is blocked by the merges atm.

The proposal is to move our parser to [qmlweb/qmlweb-parser](https://github.com/qmlweb/qmlweb-parser) and have that as an (optional, given gulp-qmlweb) runtime dependency for qmlweb, and as a sole qmlweb dependency for gulp-qmlweb.

qmlweb-parser would be BSD-2-Clause licensed (inherited from uglifyjs).

Refs: #143, #52.

The questions here are:
 1. Which files are we going to move?
 2. How would be the move performed?

My thoughts:
 1. I suppose that we are going to move `src/qtcore/qml/QMLBinding.js`, `src/qtcore/qml/lib/parser.js`, `src/qtcore/qml/lib/jsparser.js`.
 2. `git filter-branch` should solve it, but we should make sure that no parser-related commits get removed.

/cc @Plaristote @akreuzkamp, please weigh in.

**Comment by Plaristote** [comment]
The first proposition, of having qmlweb-parser being an optional runtime dependency for qmlweb, is the most important thing to me in this.

There's a first problem to solve about that : I think the parser is, right now, a mandatory dependency for qmlweb, even if we split it away. Because the parser files, right now, not only parser qml and javascript, to produce a tree... it also implements the code walking the tree.

So, if I'm not mistaken, the first step we have to do is to move the walker away from the parser. Again, if I'm not mistaken, this should remove the requirement of QMLBinding within qmlweb-parser (because, as long as QMLBinding is in the parser, it will be a mandatory dependency for qmlweb).

**Comment by akreuzkamp** [comment]
I request to wait with splitting off the parser until we have decided about the long term future of QmlWeb. I think, we've got some things to discuss about the direction we want to go, like going all precompiled (if so, how) or just keep things as they are. I think, that discussion has some impact on this one.

**Comment by akreuzkamp** [comment]
still splitting the convertToEngine() part off the parser seems like a good idea. (That part is only Lauris and a bit of my work, so we can easily change the license)

**Comment by labsin** [comment]
Splitting it would also be useful to implement web workers in the future.

still splitting the convertToEngine() part off the parser seems like a good
idea. (That part is only Lauris and a bit of my work, so we can easily
change the license)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/qmlweb/qmlweb/issues/173#issuecomment-209013014>

**Comment by ChALkeR** [comment]
> So, if I'm not mistaken, the first step we have to do is to move the walker away from the parser. Again, if I'm not mistaken, this should remove the requirement of QMLBinding within qmlweb-parser (because, as long as QMLBinding is in the parser, it will be a mandatory dependency for qmlweb).

@Plaristote, see #215.

**Comment by ChALkeR** [comment]
This was done in #216.
