### ISSUE TITLE
Import of JS file causes file.js/qmldir request

### ISSUE THREAD

**Issue by jhihn** [qmlweb/qmlweb#270]
I have a statement
import "theme.js" as Theme 
in my QML source. 

In or around import.js:73 there is a request made 
GET http://localhost:8080/qml/theme.js/qmldir 404 (Not Found)

I don't see that it actually loads theme.js

**Comment by ChALkeR** [comment]
> Import of JS file causes file.js/qmldir request 

This specific issue (loading `qmldir` files attempts) is fixed in 073a4a4, closing.

> I don't see that it actually loads theme.js

JS imports _should_ work, but there might be bugs (as well as in other places). If they don't work correctly with your setup for some reason — please provide a minimal reproducable testcase and open a separate issue.
