### ISSUE TITLE
Compiling QML

### ISSUE THREAD

**Issue by akreuzkamp** [qmlweb/qmlweb#303]
Hi, for quite a while already (since beginning of 2015, so quite a bit before @ChALkeR started this initiative) I'm working on a QML to JavaScript compiler. The idea is almost the same as gulp-qmlweb, but going far beyond.
It would produce javascript code, that would mainly build up the same meta object structure we already use to construct the objects. (From there we can go beyond that structure, especially by not having bindings as strings ;)).

**Why do we need that?**
First of all: The less we need to do on the client side, the better. This approach would save us the `convertToEngine` procedure.
The main reason though is our use of `with`. It's a keyword in javascript, that is deprecated and effectively kills all javascript-optimizations browsers can do. But our engine hugely relies on it. It's more or less the fundament, why the current approach of our engine can work. QmlWeb is condemned to death, when browsers decide to drop support for `with`.
The only way out is to rewrite bindings and functions on code-level, in a way that `with` isn't needed anymore. But that requires a deep understanding of the code - a symboltable and stuff, i.e. a compiler.

The compiler @jangmarker, @pavelvasev  and I started to write, is written in C++ and reuses Qt's very own parser (so less work for us) and can potentially reuse quite some more stuff.

Now I would like to start a discussion on whether we want to go for that solution in the long run. To be honest, the only alternative I see is writing a compiler in JS and doing just-in-time compilation.

**Pro** compiling with a C++ compiler:
- The code already exists
- We can reuse code from Qt, which is per definitio perfect.
- No dependency on NodeJS (only an advantage for people doing native applications normally)
  **Contra**:
- People need to install a native application to compile. With a compiler written in JS, web developers that already have NodeJS wouldn't (no disadvantage for people doing native applications normally as they're used to it)
- We couldn't offer a pre-compilation free version of QmlWeb - at least not one, that wouldn't rely on `with`.

A small discussion already started at https://github.com/qmlweb/qmlweb-parser/issues/20, I'd like to use this issue to continue the discussion.

**Comment by akreuzkamp** [comment]
@ChALkeR:

> The thing is, I want to keep QmlWeb usable from the client-side only, i.e. without the help of server-side parsing. And even with the server-side parsing, it would be great if that wouldn't require compilation of a native add-on and/or installing Qt on the server =).

Do you want to support QmlWeb without precompilation as a possibility (esp. for getting started quickly) or as the main way to use it? If it's the latter, I think we'd need to precompile anyway, for the reasons stated above. If it's the former, shouldn't the current parser be enough?

> a decent parser would allow us to implement linting for *.qml files, perhaps even on top of eslint — something that would not just fail on parsing errors, but which would highlight bad code formatting etc.

The compiler would and will just as well enable the same. Actually I know my company is quite interested in using it as a base for static code analysis for QML. A NodeJS based version, won't work for them, though, as they need integration with Qt (they want to use it for normal QML, after all ;) ). So we have someone willing to invest some time into linting and stuff, if we use a C++ compiler :)

> Also, I'm thinking about coupling a QML parser together with Babel, that would allow to use newer ECMAScript in qml files (i.e. transforming QML with newer ECMAScript syntax to QML with supported syntax).

Fair engough, with the C++ compiler, that would require Qt to support newer ECMAScript first.

**Comment by stephenmdangelo** [comment]
> The main reason though is our use of which. 

@akreuzkamp do you mean `with`?

**Comment by akreuzkamp** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with?redirectlocale=en-US&redirectslug=JavaScript%2FReference%2FStatements%2Fwith

**Comment by akreuzkamp** [comment]
Btw, current code is here: https://phabricator.kde.org/diffusion/QMLWEB/browse/development%252Fqmlweb2/ (quite some stuff is also still stuck in review requests, there...)

**Comment by stephenmdangelo** [comment]
@akreuzkamp So would your ideal scenario be that the C++ compiler be integrated into this code base? Or does use of the C++ compiler mean that most of this code base goes away, as it's handled as part of the compilation step?

I'm just wondering where the line between the output of the compiler and the Javascript here is drawn.

Do the actual Item->DOM implementations stay as they are here? It appears that stuff like `registerQmlType` would go away, as that's done during compilation: https://phabricator.kde.org/diffusion/QMLWEB/browse/development%252Fqmlweb2/src/qmljsc/moduleloading/qtqmlmoduleloader.cpp;6be397d228e390bd92921e69707dcd3189724ea6$96

I mostly just want to know where the best places are to focus my efforts (e.g. do we need #239 if it's all just going to be replaced with the C++ compiler?).

**Comment by akreuzkamp** [comment]
Still I think #239 makes sense, until we are at the point, that we can actually compile that. :)

**Comment by ChALkeR** [comment]
@akreuzkamp, I also think that we should have a compiler of some sort, that transforms QML modules/files to something close to how we define modules now. I planned on having that one implemented in js, though.

> `which`

s/which/with/g :smile: 

> It's a keyword in javascript, that is deprecated and effectively kills all javascript-optimizations browsers can do.

Recommended against — sure. Kills all javascript optimizations — wrong, TurboFan can optimize it and that optimization is enabled by default in v8 (since not so long ago).

> Do you want to support QmlWeb without precompilation as a possibility (esp. for getting started quickly) or as the main way to use it?

Both =). I want it be equally usable with a client-side parser (i.e. with no preprocessing required) and with server-side parsing (to speed things up, this is going to be the recommended way).

> If it's the former, shouldn't the current parser be enough?

No. I want proper linting for QML done in js (think eslint), editors support (e.g. Atom, Eclipse also has a qml parser in js it seems, see https://github.com/qmlweb/acorn-qml/issues/2), and (in future) the ability to transform QML code, e.g. fixing code formatting and for transforming the js part of the QML code using Babel, for example.

The current parser is not fit for that. Also, the upstream (UglifyJS@1) is not maintained, and porting to UglifyJS@2 doesn't seem to be a better solution that to rewrite everything as a plugin to a proper stand-alone js parser (like acorn).

---

Perhaps we need just to make things more abstract here, and move the parts of QmlWeb that wouldn't be needed when everything is compiled into a separate library that could be loaded separately as qmlweb-parser can now.

That would give us a separate common runtime, and we could still implement two different parsers (c++/js) and compilers (c++/js) to serve different needs.

Btw, I believe we already discussed that in IRC some time ago :smile:.

**Comment by ChALkeR** [comment]
@akreuzkamp Btw, any chances that the C++ parser could be used to produce the AST in the [estree](https://github.com/estree/estree)-compatible format?

**Comment by akreuzkamp** [comment]
> I want proper linting for QML done in js (think eslint)

Why isn't linting done in the compiler enough?

> and (in future) the ability to transform QML code, e.g. fixing code formatting and for transforming the js part of the QML code using Babel, for example.

You want that to be transformed on the fly? As long as we require preprocessing for that (as it is for pure js as well), we can easily integrate that step into the compiler :) Code-formatting is "fixed" by the compiler anyway :)

Editor support is quite off topic for qmlweb, imo, but acorn-qml seems like a good option for that anyway ;)

That being said: If it turns out, we can use acorn-qml instead of writing our own qml parser, it's obviously worth it in any way to replace the current one. :)

> Btw, any chances that the C++ parser could be used to produce the AST in the estree-compatible format?
I don't see why, to be honest. The C++ compiler would output all js-code as (slightly modified) js-code. QML code could be transformed to something like an AST, but imo AST doesn't make sense. We'd need something more highlevel (like our meta-object structure is)

+1 for a shared runtime, with different parsers/compilers. Still it's worth a discussion, how much development time we want to spend on either parser/compiler ;)

Yes, we discussed some stuff in IRC :) But I want to have that discussion with the rest as well and as it seems, there's still some items open :)

**Comment by ChALkeR** [comment]
>> I want proper linting for QML done in js (think eslint)
> Why isn't linting done in the compiler enough?

Check what [eslint](http://eslint.org/) can do =). See its [rules](http://eslint.org/docs/rules/).
With a proper parser tree we could even reuse eslint to lint the js parts of QML, and add our own (user-configurable) set of rules for linting the QML parts.

> You want that to be transformed on the fly?

Nope, not for QmlWeb. That could be used anywhere, though — e.g. people could write QML code with newer ECMAScript, transform it, and use with Qt QML in their projects.

> Still it's worth a discussion, how much development time we want to spend on either parser/compiler ;)

I don't think that we could decide that somehow in advance ;-). Let's just see how things turn out.

> Yes, we discussed some stuff in IRC :) But I want to have that discussion with the rest as well and as it seems, there's still some items open :)

Sure.

**Comment by labsin** [comment]
I started working on a parser based on esparser using the AST before the
QmlWeb team. It just includes the es libs.

It's easy to use escope on a part of the AST to replace objects in the
global scope with a wrapper to get the metaobject to avoid with and have
better control on the scope.

I want proper linting for QML done in js (think eslint)
Why isn't linting done in the compiler enough?

Check what eslint <http://eslint.org/> can do =). See its rules
<http://eslint.org/docs/rules/>.
With a proper parser tree we could even reuse eslint to lint the js parts
of QML, and add our own (user-configurable) set of rules for linting the
QML parts.

You want that to be transformed on the fly?

Nope, not for QmlWeb. That could be used anywhere, though — e.g. people
could write QML code with newer ECMAScript, transform it, and use with Qt
QML in their projects.

Still it's worth a discussion, how much development time we want to spend
on either parser/compiler ;)

I don't think that we could decide that somehow in advance ;-). Let's just
see how things turn out.

Yes, we discussed some stuff in IRC :) But I want to have that discussion
with the rest as well and as it seems, there's still some items open :)

Sure.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/qmlweb/qmlweb/issues/303#issuecomment-232128629>, or mute
the thread
<https://github.com/notifications/unsubscribe/ABH0SXbnrCBHuFa0eEwH0RMxzt92Kl9Tks5qU9aegaJpZM4JKgsZ>
.

**Comment by Plaristote** [comment]
Sounds good to me. I'd love to get rid of most of the QML parts and have qmlweb focused on implementing QML components for the browser.

**Comment by labsin** [comment]
Btw

Why do you want to also write a qmllint if it already exists:
https://www.kdab.com/kdab-contributions-qt-5-4-qmllint/
Op 14 jul. 2016 17:02 schreef "Plaristote" <notifications@github.com>:

**Comment by ChALkeR** [comment]
@labsin I am aware of that and it's a different tool. Correct me if I'm wrong, but doesn't that tool just report fatal errors? I want to be able to enforce code style and spot potential run-time logical errors.

**Comment by akreuzkamp** [comment]
To do that, you'll need a deep understanding of the code, i.e. not only a parser, but symbol tables, control flow graphs, etc. in other words, you need (almost) a compiler...

**Comment by labsin** [comment]
QtCreator can also reformat the file.
It's under Tools->QML.
If you want to, it should be possible to make a tool out of it. It's open
source after all.

Op 15 jul. 2016 11:35 schreef "akreuzkamp" <notifications@github.com>:

**Comment by labsin** [comment]
@ChALkeR 
So today I gave it a shot and got the Reformatter from QtCreator to work as a CLI.
It's over at https://github.com/labsin/qmljsreformatte.
The repo pulls in the QtCreator source because the dev packages of QtCreator don't expose the needed libs.

It's not tested a lot but seems to work.
Please tell me if it's not.

**Comment by pavelvasev** [comment]
* Is it possible to use Qt source code in terms of [Qt license](http://doc.qt.io/qt-5/opensourcelicense.html)? I mean, it seems will force QmlWeb/C++ to be LGPL. And then, every project which ships with it, should be LGPL too?.. Or it should install QmlWeb/C++ as a third-party dependency?...

* In any case, I vote for most number of shared things as possible ;-)

**Comment by akreuzkamp** [comment]
It is possible to use Qt source code in a compiler. As long as we only link against Qt code it will obviously won't force us to use any license. If we copy'n'paste Qt code (which I plan to do), it would force us to use GPL (or LGPL, but that doesn't make sense) as a license. But as it's native code, I don't see, why we should use another license.
Using GPL as a license for the compiler has no implications about the license of the runtime code or even the compiled code (we already have different licenses for parser and runtime, after all).

**Comment by pavelvasev** [comment]
Thank you Anton!

> Using GPL as a license for the compiler has no implications about the license of the runtime code or even the compiled code 

This is until you don't include GPL project in source tree of other project, right?

**Comment by akreuzkamp** [comment]
Almost. It doesn't exactly matter, what you include in your source tree. It matters, what code you *distribute*. If you've got a proprietary project using qmlweb and they decide to copy the source code of qmlweb into their source repo, that doesn't hurt the GPL, as they're not going to distribute any GPL code.

Afaik, even if they open up their code repository, it isn't a problem, as long as the GPL code is still clearly separated from the rest and *can be run on it's own.* You hurt the GPL as soon as the GPL stuff you used can't be run anymore, without needing Non-GPL code (i.e. as soon as the compiler-binary includes non-GPL code)

Does that answer you question or did you mean to ask something completely different?

**Comment by pavelvasev** [comment]
Ok Anton, thank you very much! I think your answer is sufficient for me... ;)

**Comment by labsin** [comment]
I also think it should be possible to compile qml on the fly. Dynamic
objects are an important aspect of qml.

Op 18 jul. 2016 14:50 schreef "Pavel Vasev" <notifications@github.com>:

**Comment by akreuzkamp** [comment]
Dynamic objects is no problem, you can import compiled files just as good as you can import qml files ;)
All you need to do is to compile each qml file you have and then you just use `Qt.createComponent("foo.qml")` and the runtime would know that it's supposed to load `foo.qml.js` (or whatever ending the compiled qml files get)

**Comment by labsin** [comment]
I also meant dynamic objects from a string that represents qml. I already
saw it a couple of times in a qml app.
Although I would be fine without it, it's another break with the At Qml

Op 18 jul. 2016 16:11 schreef "akreuzkamp" <notifications@github.com>:

**Comment by ChALkeR** [comment]
@labsin I believe we could support both — the pre-compilation and the runtime compilation (with parser/compiler auto-loading).

**Comment by akreuzkamp** [comment]
To keep you up-to-date: I effectively stopped working on this, as its reception wasn't too enthusiastic. Consider this idea mainly dead.
