### ISSUE TITLE
Animations on properties should not fail if there is no default property

### ISSUE THREAD

**Issue by ChALkeR** [qmlweb/qmlweb#372]
This should work:
```qml
import QtQuick 2.6

Item {
  transform: Rotation {
    NumberAnimation on angle {
    }
  }
}
```

This shouldn't:

```qml
import QtQuick 2.6

Item {
  transform: Rotation {
    NumberAnimation {
    }
  }
}
```

```qml
import QtQuick 2.6

Item {
  QtObject {
    NumberAnimation {
    }
  }
}
```

All of the above currently crash with «Cannot assign to non-existent default property», but that shouldn't be the case for the first one.

/cc @qmlweb/collaborators, ideas how Qt does that and/or how we should handle those?

The code in question is at [src/engine/properties.js#L77](https://github.com/qmlweb/qmlweb/blob/840ebe6cf69feefe5d39a854d76c6bbad9663fdd/src/engine/properties.js#L77).

**Comment by Plaristote** [comment]
This happens because Rotation inherits QtObject instead of Item.
Sounds to me like we should just move the `defaultProperty` from Item (`data`) into QtObject. It does fix the issue.

As for the cases that shouldn't work, I think the simplest solution would be to evaluate whether `property` or `properties` is set at the end of the constructor (the `on` being evaluated over there, in PropertyAnimation).
